### ISSUE TITLE
CSS broken in timeline

### ISSUE THREAD

**Issue by rajagopal28** [Oreoz/ember-vertical-timeline#8]
I am using this timeline plugin in my app and the CSS seems to be broken. I am using ember-paper framework in my app. Adding screenshot. Here is the link to see my app with sample timeline data. https://rajagopal28.github.io/Nike/#/users . It would be great if you help me fix the style.
![image](https://user-images.githubusercontent.com/11327536/31925775-8c8c30c6-b8a8-11e7-964d-eb3b23ae1c1e.png)

**Comment by Oreoz** [comment]
It looks to me like your container is way too narrow. The mobile look only triggers when the screen is detected to be of small size.

If you enlarge your container, it'll look like this. (I removed the `layout-column` class from your container to demonstrate)

![image](https://user-images.githubusercontent.com/3945623/32050611-71e36c26-ba1f-11e7-8462-c6e029e0f66f.png)
